#!/usr/bin/env bash
# Script: 0-change_your_home_IP
# Description: Configures the localhost and facebook.com IP addresses
# Usage: sudo ./0-change_your_home_IP

# Update the hosts file to resolve localhost to 127.0.0.2
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts >/dev/null

# Update the hosts file to resolve facebook.com to 8.8.8.8
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts >/dev/null

# Clear the DNS cache
sudo /etc/init.d/networking restart

# End of script
