#!/usr/bin/env bash
# Script: 0-change_your_home_IP
# Description: Configures the localhost and facebook.com IP addresses
# Usage: sudo ./0-change_your_home_IP

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
